Updated init script for wildfly 10

diff --git a/templates/wildfly_initd.j2 b/templates/wildfly_initd.j2
--- a/templates/wildfly_initd.j2
+++ b/templates/wildfly_initd.j2
@@ -47,6 +47,10 @@ if [ -z "$SHUTDOWN_WAIT" ]; then
 	SHUTDOWN_WAIT=30
 fi
 
+if [ -z "$JBOSS_LOCKFILE" ]; then
+	JBOSS_LOCKFILE=/var/lock/subsys/wildfly
+fi
+
 # Startup mode of wildfly
 if [ -z "$JBOSS_MODE" ]; then
 	JBOSS_MODE=standalone
@@ -58,6 +62,7 @@ if [ "$JBOSS_MODE" = "standalone" ]; then
 	if [ -z "$JBOSS_CONFIG" ]; then
 		JBOSS_CONFIG=standalone.xml
 	fi
+	JBOSS_MARKERFILE=$JBOSS_HOME/standalone/tmp/startup-marker
 else
 	JBOSS_SCRIPT=$JBOSS_HOME/bin/domain.sh
 	if [ -z "$JBOSS_DOMAIN_CONFIG" ]; then
@@ -66,19 +71,11 @@ else
 	if [ -z "$JBOSS_HOST_CONFIG" ]; then
 		JBOSS_HOST_CONFIG=host.xml
 	fi
+	JBOSS_MARKERFILE=$JBOSS_HOME/domain/tmp/startup-marker
 fi
 
 prog='wildfly'
-
-CMD_PREFIX=''
-
-if [ ! -z "$JBOSS_USER" ]; then
-	if [ -r /etc/rc.d/init.d/functions ]; then
-		CMD_PREFIX="daemon --user $JBOSS_USER"
-	else
-		CMD_PREFIX="su - $JBOSS_USER -c"
-	fi
-fi
+currenttime=$(date +%s%N | cut -b1-13)
 
 start() {
 	echo -n "Starting $prog: "
@@ -98,22 +95,24 @@ start() {
 
 	mkdir -p $(dirname $JBOSS_PIDFILE)
 	chown $JBOSS_USER $(dirname $JBOSS_PIDFILE) || true
-	#$CMD_PREFIX JBOSS_PIDFILE=$JBOSS_PIDFILE $JBOSS_SCRIPT 2>&1 >> $JBOSS_CONSOLE_LOG &
-	#$CMD_PREFIX JBOSS_PIDFILE=$JBOSS_PIDFILE $JBOSS_SCRIPT &
 
 
-    if [ ! -z "$JBOSS_USER" ]; then
+	if [ ! -z "$JBOSS_USER" ]; then
 		if [ "$JBOSS_MODE" = "standalone" ]; then
 			if [ -r /etc/rc.d/init.d/functions ]; then
+				cd $JBOSS_HOME
 				daemon --user $JBOSS_USER LAUNCH_JBOSS_IN_BACKGROUND=1 JBOSS_PIDFILE=$JBOSS_PIDFILE $JBOSS_SCRIPT -c $JBOSS_CONFIG $JBOSS_OPTS >> $JBOSS_CONSOLE_LOG 2>&1 &
+				cd -
 			else
-				su - $JBOSS_USER -c "LAUNCH_JBOSS_IN_BACKGROUND=1 JBOSS_PIDFILE=$JBOSS_PIDFILE $JBOSS_SCRIPT -c $JBOSS_CONFIG $JBOSS_OPTS" >> $JBOSS_CONSOLE_LOG 2>&1 &
+				su - $JBOSS_USER -c "cd $JBOSS_HOME; LAUNCH_JBOSS_IN_BACKGROUND=1 JBOSS_PIDFILE=$JBOSS_PIDFILE $JBOSS_SCRIPT -c $JBOSS_CONFIG $JBOSS_OPTS" >> $JBOSS_CONSOLE_LOG 2>&1 &
 			fi
 		else
 			if [ -r /etc/rc.d/init.d/functions ]; then
+				cd $JBOSS_HOME
 				daemon --user $JBOSS_USER LAUNCH_JBOSS_IN_BACKGROUND=1 JBOSS_PIDFILE=$JBOSS_PIDFILE $JBOSS_SCRIPT --domain-config=$JBOSS_DOMAIN_CONFIG --host-config=$JBOSS_HOST_CONFIG $JBOSS_OPTS >> $JBOSS_CONSOLE_LOG 2>&1 &
+				cd -
 			else
-				su - $JBOSS_USER -c "LAUNCH_JBOSS_IN_BACKGROUND=1 JBOSS_PIDFILE=$JBOSS_PIDFILE $JBOSS_SCRIPT --domain-config=$JBOSS_DOMAIN_CONFIG --host-config=$JBOSS_HOST_CONFIG $JBOSS_OPTS" >> $JBOSS_CONSOLE_LOG 2>&1 &
+				su - $JBOSS_USER -c "cd $JBOSS_HOME; LAUNCH_JBOSS_IN_BACKGROUND=1 JBOSS_PIDFILE=$JBOSS_PIDFILE $JBOSS_SCRIPT --domain-config=$JBOSS_DOMAIN_CONFIG --host-config=$JBOSS_HOST_CONFIG $JBOSS_OPTS" >> $JBOSS_CONSOLE_LOG 2>&1 &
 			fi
 		fi
 	fi
@@ -123,15 +122,25 @@ start() {
 
 	until [ $count -gt $STARTUP_WAIT ]
 	do
-		grep 'JBAS015874:' $JBOSS_CONSOLE_LOG > /dev/null
-		if [ $? -eq 0 ] ; then
-			launched=true
-			break
-		fi
 		sleep 1
 		let count=$count+1;
+		if [ -f $JBOSS_MARKERFILE ]; then
+			markerfiletimestamp=$(grep -o '[0-9]*' $JBOSS_MARKERFILE) > /dev/null
+			if [ "$markerfiletimestamp" -gt "$currenttime" ] ; then
+				grep -i 'success:' $JBOSS_MARKERFILE > /dev/null
+				if [ $? -eq 0 ] ; then
+					launched=true
+					break
+				fi
+			fi
+		fi
 	done
 
+	if [ "$launched" = "false" ] ; then
+		echo "$prog started with errors, please see server log for details"
+	fi
+
+        touch $JBOSS_LOCKFILE
 	success
 	echo
 	return 0
@@ -158,6 +167,7 @@ stop() {
 		fi
 	fi
 	rm -f $JBOSS_PIDFILE
+	rm -f $JBOSS_LOCKFILE
 	success
 	echo
 }
@@ -193,7 +203,7 @@ case "$1" in
 		;;
 	*)
 		## If no parameters are given, print which are avaiable.
-		echo "Usage: $0 {start|stop|status|restart|reload}"
+		echo "Usage: $0 {start|stop|status|restart}"
 		exit 1
 		;;
 esac
